### ISSUE TITLE
MacOS Bundling Issue

### ISSUE THREAD

**Issue by e3ndr** [jcefmaven/jcefbundlemavenplugin#1]
Howdy!

I am able to create a bundle for MacOS however when my program tries to load CEF I get an `UnsatisfiedLinkError`.  
I have checked the contents of the app bundle to make sure that it's at least copying the natives over, which it is.  
When I launch the .app it'll just hang and I'll need to force quit it, when I navigate into the bundle in terminal and execute `JavaAppLauncher` directly I can get the console output which spits out an `UnsatisfiedLinkError`.

Also, I am unable to copy my own `CefIcon.icns` using a relocation.
```xml
<relocation>../app_icon.icns:../Resources/CefIcon.icns</relocation>
```
results in:
```
[ERROR] Failed to execute goal org.cef:jcef-bundle-maven-plugin:1.0:macosx64 (macos) on project Caffeinated-MacOS: An error occurred while creating the bundle: Failed to create file /Users/alex/Documents/CodeProjects/Casterlabs/casterlabs-caffeinated/casterlabs-caffeinated/app-framework/Build/Caffeinated-MacOS/target/jcef-bundle-macosx64/casterlabs-caffeinated.app/Contents/Java/../Resources/CefIcon.icns -> [Help 1]
```

I have verified that bundling for Windows works perfectly fine, I have not tested Linux to see if it's just a project structure issue. (though I assume Linux and Windows share the same structure and thus wouldn't act any different)

Thanks for your time!
(If you want access to the source code for debugging let me know and I'll add you to the repo (it's currently private))

**Comment by FriwiDev** [comment]
Hey there, I'm currently in the process of updating the maven support for JCEF. I'm already building the most up to date versions (see https://github.com/jcefmaven/jcefbuild) and I plan to add a new maven support for these builds in the next two weeks. The MacOS version will not require a bundle to work then, which will most probably fix your problems on MacOS anyways. Is that ok for you, or does your problem on MacOS require immediate fixing?

**Comment by e3ndr** [comment]
Perfect, I'll just wait for the new version instead. Cheers!
